### ISSUE TITLE
Kode pos tidak lengkap jika dibandingkan dengan `cahyadsn/wilayah`

### ISSUE THREAD

**Issue by feryardiant** [w3appdev/kodepos#1]
Halo, pertama2 terima kasih banyak atas repo ini yang cukup membantu pada beberapa project saya.

Tapi ternyata diketahui bahwa kodepos yang disediakan masih belum lengkap dan terdapat 4577 kelurahan yang belum tercantum. Dalam hal ini saya bandingkan dengan kode wilayah yang di provide [`cahyadsn/wilayah`](https://github.com/cahyadsn/wilayah), selengkapnya saya cantumkan di repo saya https://github.com/creasico/laravel-nusa/issues/41.

Pertanyaan saya, adakah rencana untuk update & melengkapi datanya?

Terima kasih

**Comment by w3appdev** [comment]
Hai @feryardiant. Repo ini murni hasil scrapping dari www.nomor.net jadi bukan saya maintainernya. Harap maklum. 

Saya belum sempat untuk explore lebih jauh, tapi berdasarkan data di repo Anda  [creasico/laravel-nusa#41](https://github.com/creasico/laravel-nusa/issues/41#issuecomment-1799799950)
7 data dengan kode-wilayah yang berbeda dengan yang Anda gunakan, itu sudah saya periksa semua dan valid. Juga tidak ada kolom kode pos yang NULL.

Melalui Google bisa kita periksa. Saya beri contoh untuk kelurahan Kemall yang kode wilayahnya 95.08.01.2008.

input Google search box `kode wilayah 95.08.01.2008`

hasilnya kode tersebut dikenal dan telah digunakan oleh beberapa pihak diluar www.nomor.net, seperti 
[Universitas Pandanaran Semarang](https://p2k.unpand.ac.id/_a.php?_a=desa-kecamatan-kota&tanda=kota&prov=Papua&provkot=Kab.+Nduga&desa=Kemali&kec1=Kenyam )

demikian juga untuk 6 kelurahan lainnya

sedangkan untuk kelurahan Kemall dengan kode 9508012002 tidak dikenal (meskipun setelah saya sesuaikan kodenya menjadi 95.08.01.2002).

Saya juga perhatikan hanya data propinsi Papua Pegunungan yang terdampak. Mungkin belum data final? Karena propinsi tersebut termasuk propinsi baru. 

Terima kasih atas perhatiannya.

**Comment by feryardiant** [comment]
Terima kasih respon nya,

Dalam hal ini, mungkin bisa saya simpulkan bahwa data yang di provide oleh nomor.net memang tidak/belum sama dengan data [Kepmendagri No 100.1.1-6117 Tahun 2022](https://commons.wikimedia.org/wiki/File:Kepmendagri_Nomor_100.1.1-6117_Tahun_2022.pdf).

![Screenshot 2023-11-08 at 14 56 59](https://github.com/w3appdev/kodepos/assets/508665/e81194ec-4268-474a-a12c-b4b22b41b63f)

Dimana di dokumen kepmendagri tersebut kode `95.08.01.2002` adalah kelurahan Kemali, dan `95.08.01.2008` adalah kelurahan Ulunmu. Sedangkan di nomor.net `95.08.01.2008` adalah kelurahan Kemali dan `95.08.01.2002` tidak ada.

**Comment by w3appdev** [comment]
@feryardiant , rasanya saya juga pernah di posisi Anda. Hanya saja saya sempat monitor sampai data final disepakati dan berlaku. 

Kelihatannya memang ada revisi tapi tidak dipublikasi. Saya juga sebelumnya merujuk Kepmendagri No 100.1.1-6117 Tahun 2022 yang sama. Tapi tidak lama berselang ada kabar menyusul (setelah dokumen dirilis) bahwa masih ada propinsi baru yang akan diresmikan (tp lupa kapannya). Akhirnya saya putuskan merujuk ke www.nomor.net karena saya anggap lebih simpel dan meyakinkan.

Untuk membantu meyakinkan Anda coba lihat hal 16 file PDF Kepmendagri rujukan, di situ tertera jumlah propinsi masih 37. Sedangkan isu baru yang saya dengar total propinsi akan menjadi 38. Jadi isi dokumen yang saat itu saya rujuk sudah tidak valid dan, itu juga yang saya maksud dengan 'Mungkin belum data final?' di atas.

**Comment by feryardiant** [comment]
I see, makasih banyak atas waktu nya pak.

Issue ini saya close ya 😁
