### ISSUE TITLE
Problem Database Jika Pengguna Over 10.000

### ISSUE THREAD

**Issue by dearlypebriano** [w3appdev/kodepos#2]
Halo mas, izin bertanya, jika sudah memiliki website public dengan users over 10.000, lebih baik menggunakan Database NoSQL / MySQL??, Jika NoSQL, Database apakah yang cocok, dan jika MySQL, Maka database apa yang cocok?, Terimakasih🙏

**Comment by straycoders** [comment]
di google aja jawaban lebih komplet mas :mag: :smile:

**Comment by dearlypebriano** [comment]
> di google aja jawaban lebih komplet mas 🔍 😄

baik mas terimakasih informasinya
